### ISSUE TITLE
google responses exceptions.TypeError: Data must not be unicode

### ISSUE THREAD

**Issue by diarized** [diarized/irc_news#5]
IRC session:

```
13:17 | noneo > Spurr1Bot: google ala ma kota
13:17 | Spurr1Bot > Looking for plugin google
13:17 | Spurr1Bot > American Library Association
```

Stack trace:

```
2016-02-24 13:17:27+0100 [LogBot,client] Unhandled Error
        Traceback (most recent call last):
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2516, in dataReceived
            basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2524, in lineReceived
            self.handleCommand(command, prefix, params)
        --- <exception caught here> ---
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2579, in handleCommand
            method(prefix, params)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1944, in irc_PRIVMSG
            self.privmsg(user, channel, message)
          File "./log_bot.py", line 129, in privmsg
            self.msg(channel, response)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1631, in msg
            self.sendLine(fmt + line)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1117, in sendLine
            self._reallySendLine(line)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1113, in _reallySendLine
            return basic.LineReceiver.sendLine(self, lowQuote(line) + '\r')
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 635, in sendLine
            return self.transport.write(line + self.delimiter)
          File "/home/artur/Scripts/Python/lib/python2.7/site-packages/twisted/internet/abstract.py", line 348, in write
            raise TypeError("Data must not be unicode")
        exceptions.TypeError: Data must not be unicode
```

**Comment by diarized** [comment]
Solved in 936120e
